use_frameworks!

#source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'QAXQRCode_Example' do
  pod 'QAXQRCode', :path => '../'
#  pod 'QAXQRCode' #同source 一起用

  target 'QAXQRCode_Tests' do
    inherit! :search_paths

    
  end
end
